### ISSUE TITLE
Find a text classifier from Weka packages

### ISSUE THREAD

**Issue by damirsaleschoice** [Sales-Choice-Volunteering-Project/EmotionAnalyzerWeka#15]
Find, but DO NOT INSTALL !!! - Weka can break. I will check the installation instead and see if it is a GO or NOT-GO.
Search the packages for any text-classifier with any keywords you can think of, even the word "twitter" can apply.
Make a list of packages we may find interesting for sentiment analysis.

You can also search the full list, may be a bit tedious, but it is sometimes better to be thorough.

**Comment by sherlockliang888** [comment]
Text Classification:
DMNBtext: Class for building and using a Discriminative Multinomial Naive Bayes classifier
AffectiveTweets: Text Filters for Analyzing Sentiment and Emotions of Tweets
SparseGenerativeModel:	Sparse Generative Model
bayesianLogisticRegression: Implements Bayesian Logistic Regression for both Gaussian and Laplace Priors

Multiclass classification:
WiSARD: multi-class classifier using the WiSARD weightless neural network model. 


There are some people using AffectiveTweets for sentiment analysis, so that would work I think. I will need to do some research on how other packages are used.

**Comment by damirsaleschoice** [comment]
Thanks, I will send the purolator data and will try installing the classifiers as soon as I get some free time.

**Comment by damirsaleschoice** [comment]
SparseGenerativeModel broke the startup logo but is safe to install.
Everything else is safe to install.
